Models/ErrorViewModel.cs
namespace MeetingApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MeetingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository 
    {
        private static List<UserInfo> _users = new();

        static Repository()
        {
            _users.Add(new UserInfo() { Id=1, Name = "Ali", Email = "ali@gmailcom", Phone = "05437769468", WillAttend = true});
            _users.Add(new UserInfo() { Id=2, Name = "Ahmet", Email = "ahmet@gmailcom", Phone = "05437723235", WillAttend = false});
            _users.Add(new UserInfo() { Id=3, Name = "Can", Email = "can@gmailcom", Phone = "054377236536", WillAttend = true});
        }

        public static List<UserInfo> getUsers {
            get {
                return _users;
            }
        }

        public static void addUser(UserInfo user)
        {
            user.Id = getUsers.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Ad alanı zorunlu")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Telefon alanı zorunlu")]
        [MinLength(11, ErrorMessage = "Telefon en az 11 eleman içermelidir.")]
        public string? Phone { get; set; } 

        [Required(ErrorMessage = "Email alanı zorunlu")]
        [EmailAddress]
        public string? Email { get; set; } 

        [Required]
        public bool WillAttend { get; set; } 

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        ViewData["greeting"] = DateTime.Now.Hour > 12 ? "İyi Günler" : "Günaydın";
        ViewBag.UserCount = Repository.getUsers.Where(i => i.WillAttend == true).Count();
        var meetingInfo = new MeetingInfo() {
            Id = 1,
            Location = "İstanbul",
            Date = new DateTime(2024, 01, 20, 20, 0, 0),
            NumberOfPeople = 100
        };

        return View(meetingInfo);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MeetingApp.Models;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        private readonly ILogger<MeetingController> _logger;

        public MeetingController(ILogger<MeetingController> logger)
        {
            _logger = logger;
        }
 
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {

            if(ModelState.IsValid) {
                Repository.addUser(model);
                ViewBag.UserCount = Repository.getUsers.Where(i => i.WillAttend == true).Count();
                return View("Thanks", model);
            } else {
                return View(model);
            }
       
        }

        [HttpGet]
        public IActionResult List()
        {
            return View(Repository.getUsers);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
    ViewData["Title"] = "Home";
    Layout = "_Layout2";
}
<main class="text-center">
    <h1 class="h4">@ViewData["greeting"]</h1>
    <p>Toplantıya katılım durumu bildir.</p>
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek.</li>
            <li class="list-group-item">@ViewBag.UserCount katılımcı</li>

        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply" >Başvuru Yap</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewData["Title"] = "Başvuru Formu";
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form action="" method="post">
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Attendance Status</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="true">Evet, Geliyorum.</option>
            <option value="false">Hayır, Gelmiyorum.</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewData["title"] = "Başvuru Detayı";
}
@{
     var status = @Model.WillAttend ? "Katılıyor" : "Katılmıyor";
     var className = @Model.WillAttend ? "success" : "danger";

}
<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p class="bg-@className">
        @status
    </p>
    <p>İsim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Phone: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
<main class="text-center">
    <h1 class="h4">Toplantıya katılım lsitesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @{ int i = 0; }
            @foreach(var user in Model)
            {
                var status = user.WillAttend ? "Evet" : "Hayır";
                var className = user.WillAttend ? "table-success" : "table-danger";

                if(user.WillAttend) i++;

                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@status</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
            }

            <div class="card">
                <div class="card-body">
                    <span>Katılımcı sayısı: @i</span>
                </div>
            </div>

        </tbody>
    </table>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo

<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>

    @if(Model.WillAttend)
    {
        <p>Teşekkürler, @Model.Name <table></table>Toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
        <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="List">Katılımcıları Listele</a>
    } else {
        <p>@Model.Name, katılamadığından dolayı üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="meeting/apply">Başvuru Formu</a>

    }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeetingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeetingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeetingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="Index">Meeting</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> -->
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MeetingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeetingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeetingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeetingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Meeting" asp-action="Index">Meeting</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> -->
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MeetingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>